### PR TITLE
torch: make dropout optional

### PR DESCRIPTION
**Pull request by AliciaCurth**

### CODE REVIEW

**Comment by bcebere** [comment]
I did a test on the fork [here](https://github.com/vanderschaarlab/CATENets/actions), the tests start fine there(it's the same code).

It might be just a hiccup, try to do another commit/push, and they should start.

**Comment by bcebere** [comment]
Oh, Github suffered an outage when you tried https://www.githubstatus.com/incidents/tyc8wpsgr2r8

It should be functional again, they say.

**Comment by AliciaCurth** [comment]
@bcebere thanks for checking! Unfortunately, I pushed something new and it still doesn't seem to be triggered? I am confused :(

**Comment by bcebere** [comment]
It might be that they're still recovering from the incident, and Actions might still fail from time to time.

I think it's best just to create a new PR tomorrow, from the same branch, and it should work.

This kind of outage takes time to fix for everybody :(. Several others complain about it on twitter/hackernews, but it's little we can do other than wait.

**Comment by AliciaCurth** [comment]
Awesome, I see it now -- thanks for the support! (Patience is not my strong suit haha)

**Pull request merged**
